version: "3"
services:
  jupyter:
    image: ghcr.io/heromo/jupyter-langs:latest
    environment:
      # - TERM=xterm-256color
      - PS1='\e[92m\u\e[0m@\e[94m\h\e[0m:\e[35m\w\e[0m# '
    tty: true
    volumes:
      - ../:/workspaces/hands-on-nodejs-typescript:cached
    ports:
      - 8050:8050 # for Dash
      - 8888:8888 # for Jupyterlab
